export enum TruckStatus {
  AVAILABLE = "AVAILABLE",
  UNDER_MAINTENANCE = "UNDER_MAINTENANCE",
  OUT_OF_SERVICE = "OUT_OF_SERVICE",
  IN_TRANSIT = "IN_TRANSIT",
  LOADING = "LOADING",
  UNLOADING = "UNLOADING",
  WAITING_FOR_ASSIGNMENT = "WAITING_FOR_ASSIGNMENT",
  IDLE = "IDLE",
  ON_SALE = "ON_SALE",
}

export enum DriverStatus {
  ASSIGNED = "ASSIGNED",
  AVAILABLE = "AVAILABLE",
  ON_LEAVE = "ON_LEAVE",
}

export enum ShiftType {
  MONTHLY = "MONTHLY",
  WEEKLY = "WEEKLY",
  TRIP_BASED = "TRIP_BASED",
  KM = "KM",
}

export enum ShiftStatus {
   ACTIVE = "ACTIVE",
  DEACTIVE = "DEACTIVE",
}